name: Build

on: [push]

env:
  _microarchitecture=17

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Clone test repo
        uses: actions/checkout@v2
      - name: Build Package
        uses: ouuan/pkgbuild-action@master
        id: build-package
        with:
          path: linux-xanmod
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-xanmod-${{ github.run_id }}
          path: ${{ steps.build-package.outputs.pkgfile }}