name: Build

on: [push]

env:
  _microarchitecture: 17
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pkgname: [linux-xanmod-anbox]
    steps:
      - uses: actions/checkout@v2
      - name: Clone test repo
        run: git clone https://aur.archlinux.org/${{ matrix.pkgname }}.git
      - name: Build Package
        uses: ouuan/pkgbuild-action@master
        id: build-package
        with:
          path: ${{ matrix.pkgname }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.pkgname }}-${{ github.run_id }}
          path: ${{ steps.build-package.outputs.pkgfile }}